spring.application.name=finance_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=yezu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.add-mappings=false
