spring.main.allow-circular-references=true

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/financiza
spring.datasource.username=postgres
spring.datasource.password=yezu
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
app.jwtSecret= ======================expense=tracker=mywallet===========================
app.jwtExpirationMs=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giselemigisha53@gmail.com
spring.mail.password=gafo bhba gsvv dqko
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


# Application Properties
app.verificationCodeExpirationMs=1800000


# File Upload Configuration
app.user.profile.upload.dir=./uploads/user/profile
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
